### ISSUE TITLE
managed_components/espressif__esp-dl does not contain a component (AIV-712)

### ISSUE THREAD

**Issue by me-no-dev** [espressif/esp-dl#172]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

We are using ESP-DL in Arduino for face recognition. We have the following item in `idf_component.yaml`
```yaml
  espressif/esp-dl:
    version: "master"
    git: https://github.com/espressif/esp-dl.git
    require: public
    rules:
      - if: "target in [esp32s3, esp32s2, esp32]"
```

### Actual behavior (suspected bug)

Since your latest commit, we can no longer use it as component. Instead we get `'esp32-arduino-lib-builder/managed_components/espressif__esp-dl' does not contain a component.`

### Error logs or terminal output

```shell
CMake Error at esp-idf/tools/cmake/component.cmake:155 (message):
  Directory
  '/Users/ficeto/Desktop/ESP32/ESP-IDF-5/esp32-arduino-lib-builder/managed_components/espressif__esp-dl'
  does not contain a component.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:258 (__component_add)
  build/managed_components_list.temp.cmake:5 (idf_build_component)
  esp-idf/tools/cmake/build.cmake:555 (include)
  esp-idf/tools/cmake/project.cmake:710 (idf_build_process)
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!
```

### Steps to reproduce the behavior

Try a project with the above item in `idf_components.yaml`

### Project release version

latest master

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

Does not matter

### Shell

ZSH

**Comment by me-no-dev** [comment]
For ESP32, ESP32-S2 and ESP32-S3 (on both IDF v5.1 and v5.3) we have switched to the following component config:
```yaml
  espressif/esp-dl:
    version: "master"
    version: "af7808ba09448ce82c704455975d4cf1e4305fd7"
    git: https://github.com/espressif/esp-dl.git
    require: public
    rules:
      - if: "target in [esp32s3, esp32s2, esp32]"
```

For ESP32-P4 on IDF v5.3 we have added the following additional configs to coop with the new component structure:
```yaml
  # ESP-DL for ESP32-P4
  espressif/esp-dl2:
    version: "master"
    git: https://github.com/espressif/esp-dl.git
    path: esp-dl
    require: public
    rules:
      - if: "target in [esp32p4]"
  # ESP-DL Face Detection for ESP32-P4
  espressif/human_face_detect:
    version: "master"
    git: https://github.com/espressif/esp-dl.git
    path: models/human_face_detect
    require: public
    rules:
      - if: "target in [esp32p4]"
  # ESP-DL Pedestrian Detection for ESP32-P4
  espressif/pedestrian_detect:
    version: "master"
    git: https://github.com/espressif/esp-dl.git
    path: models/pedestrian_detect
    require: public
    rules:
      - if: "target in [esp32p4]"
```

Maybe it's a good idea to document this, since you are not published on the component registry and the functionality of the component has also changed.
